### ISSUE TITLE
Why the FLOPs of backward is twice as compute intensive as forward pass?

### ISSUE THREAD

**Issue by vastskymiaow** [mlperf-deepts/nns#9]
Hi, I want to get the backward pass FLOPs of a DNN such as ResNet. I'm confused about FLOPs(backward) = 2 * FLOPs(forward), is there any theoretical or empirical support?

**Comment by sergey-serebryakov** [comment]
Hi @vastskymiaow.

Based on mathematical model that NNS uses, backward FLOPs for Dense and Conv2D layers seem to be same. I've updated the README file, please, take a look at [Dense](https://github.com/mlperf-deepts/nns#dense) and [Con2D](https://github.com/mlperf-deepts/nns#conv1d-conv2d-conv2dtranspose) sections. If math is correct, then FLOPs for backward pass for these operators are 2x compared to forward FLOPs.

**Comment by vastskymiaow** [comment]
Thank you for your prompt reply! Your proof is very detailed and exactly correct. I've learnt a lot from your project. Nice man!
